### ISSUE TITLE
Registration drops users out of the project creation flow

### ISSUE THREAD

**Issue by kgstew** [reallocate/reallocate#33]
From /get-started clicking on the "Post a project" Button brings up the account registration modal. If you register an account, the flow bring you back to the home page. 

A user should be brought back into the project creation flow after they create an account to continue posting their project.

**Comment by kgstew** [comment]
I'm still getting this same bug. When I sign into my account through the submit project flow I get returned to the home page instead of being dropped into the select/create organization.

**Comment by scottzer0** [comment]
fixed facebook login.  linkedin is being more stuborn.

**Comment by scottzer0** [comment]
need to debug linkedin auth on heroku.  local seems to work though.

**Comment by kgstew** [comment]
Can this be pushed to beta? I still have this problem when logging in for new project creation and I am starting to make tutorial videos to help walk people through the steps
